version: "3.8"
services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "./.localstack/init.d:/docker-entrypoint-initaws.d"